= RxJPA2 — JPA2 RxJava helpers

[link="https://travis-ci.org/eraga/rxjpa2"]
image::https://api.travis-ci.org/eraga/rxjpa2.svg?branch=master[]


RxJava2 wrappers for blocking JPA2 operations using Kotlin extension functions.

Based on JPA `javax.persistence-api` package version 2.2

== How to use

=== Library setup

Add custom maven repository
```gradle
repositories {
    mavenCentral()
    maven {
        url 'http://nexus.eraga.net/content/repositories/public-releases/'
    }
}
```

Add gradle dependency to your project:
```gradle
compile "net.eraga.rxjpa2:helpers:1.0.0"
```

Latest version is `1.0.0`


=== Usage

Purely synthetic example how to get a single row from database with cold start
```kotlin
lateinit var entityManager: EntityManager
lateinit var entityManagerFactory: EntityManagerFactory

RxPersistence
        .createEntityManagerFactory("rxJpa2-test")
        .flatMap {
            entityManagerFactory = it
            it.rxCreateEntityManager()
        }.flatMap {
            entityManager = it
            it.rxFind(Book::class.java, 1)
        }.subscribe { book ->
            println(book.title)
            entityManager.close()
            entityManagerFactory.close()
        }
```

==== Details

`Persistence` static class was extended via `RxPersistence` kotlin object.
It has exactly the same methods as `Persistence` except they are reactive.


```kotlin
RxPersistence
        .createEntityManagerFactory("accountancy")
        .observeOn(Schedulers.computation())
        .map({
            emf.createEntityManager()
        })
        .subscribe {
            // do something with entityManager instance
        }
```

On the other hand all blocking calls of `EntityManagerFactory`, `EntityManager`, `Query` and `TypedQuery` interfaces
have got extension functions.


For example `TypedQuery.resultList` can be accessed in reactive way like that:
```kotlin
val entityManager: EntityManager = ... // instantiated somewhere else

entityManager
        .createQuery("SELECT i From Employee i order by modified desc", Employee::class.java)
        .rxResultList()
        .subscribe {
        // do something with List result
        }

```

Persisting objects inside a single transaction have become much easier
```kotlin
entityManager
        .rxTransaction {
            it.persist(Book("Transaction book 1"))
            it.persist(Book("Transaction book 2"))
            it.persist(Book("Transaction book 3"))
            it.persist(Book("Transaction book 4"))
        }
        .subscribe {
            // do something on completion
        }
```

Single persist operation is done inside a transaction
```kotlin
val book = Book("rxPersistBook")
entityManager
        .rxPersist(book)
        .subscribe {
            // do something on completion
        }
```





=== Using Schedulers

Each rx extension function can accept a `Scheduler` instance as an argument
```kotlin
// Custom Scheduler
entityManager
        .createQuery("SELECT i From Employee i order by modified desc", Employee::class.java)
        .rxResultList(Schedulers.computation())
        .subscribe {
            // do something with List result
        }
```
